services:
  - type: web
    name: dannys-cloud-os
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: NEZORA_DATA_DIR
        value: /tmp/nezora-data
      - key: NEZORA_APPS_DIR
        value: /tmp/nezora-apps
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_TOKEN
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false
    healthCheckPath: /api/healthz
    autoDeploy: true
