kind = "web"
previewPath = "/"
title = "Nezora Deploy"
version = "1.0.0"
id = "artifacts/nezora"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25611

[services.development]
run = "pnpm --filter @workspace/nezora run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nezora", "run", "build" ]
publicDir = "artifacts/nezora/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25611"
BASE_PATH = "/"
