const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#007AFF",
    background: "#F2F2F7",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#007AFF",
    primaryForeground: "#FFFFFF",
    secondary: "#E9E9EB",
    secondaryForeground: "#1C1C1E",
    muted: "#E9E9EB",
    mutedForeground: "#8E8E93",
    accent: "#EAF3FF",
    accentForeground: "#007AFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    success: "#34C759",
    successForeground: "#FFFFFF",
    warning: "#FF9500",
    warningForeground: "#FFFFFF",
    border: "#E5E5EA",
    input: "#F2F2F7",
    tabBar: "#FFFFFF",
    separator: "#C6C6C8",
  },

  dark: {
    text: "#FFFFFF",
    tint: "#0A84FF",
    background: "#070B14",
    foreground: "#FFFFFF",
    card: "#0F1628",
    cardForeground: "#FFFFFF",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#141D35",
    secondaryForeground: "#FFFFFF",
    muted: "#141D35",
    mutedForeground: "#6B7DB3",
    accent: "#1E2D4F",
    accentForeground: "#60A5FA",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    success: "#30D158",
    successForeground: "#FFFFFF",
    warning: "#FF9F0A",
    warningForeground: "#FFFFFF",
    border: "#1A2540",
    input: "#0F1628",
    tabBar: "#0A0E1C",
    separator: "#1A2540",
  },

  radius: 16,
};

export default colors;
